# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TfManage2 < Formula
  desc "Terraform workspace manager with enhanced CI/CD detection and interactive commands"
  homepage "https://github.com/sorinlg/tf-manage2"
  version "0.2.1"
  license "MIT"

  depends_on "terraform" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sorinlg/tf-manage2/releases/download/v0.2.1/tf-manage2_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "88936740f771f6b17ef8444a99460efc876df755c2342f92a1804308aa63b234"

      def install
        bin.install "tf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sorinlg/tf-manage2/releases/download/v0.2.1/tf-manage2_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "e686b64294c271e8930d8097dd49693ea25df96acdf70e1ca1cdca752552b928"

      def install
        bin.install "tf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/sorinlg/tf-manage2/releases/download/v0.2.1/tf-manage2_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "0bf0bd2f5c5addf636bfa9f914eed8a459c14486f5600fe829b4c67071443409"
      def install
        bin.install "tf"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/sorinlg/tf-manage2/releases/download/v0.2.1/tf-manage2_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "129bb9592e0004662ceccfb1b4495158a9c0af23475058248a67d7a2e23582c7"
      def install
        bin.install "tf"
      end
    end
  end

  test do
    system "#{bin}/tf", "--help"
  end
end
