# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TfManage2 < Formula
  desc "Terraform workspace manager with enhanced CI/CD detection"
  homepage "https://github.com/sorinlg/tf-manage2"
  version "0.7.0"
  license "MIT"

  depends_on "terraform" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sorinlg/tf-manage2/releases/download/v0.7.0/tf-manage2_Darwin_x86_64.tar.gz"
      sha256 "c7afadff32cd42cf52411ac815344359e69c1daf5d25978052fea94e654be7f3"

      def install
        bin.install "tf"
        bash_completion.install "bin/tf_complete.sh" => "tf"
        zsh_completion.install "bin/tf_complete.zsh" => "_tf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sorinlg/tf-manage2/releases/download/v0.7.0/tf-manage2_Darwin_arm64.tar.gz"
      sha256 "2d0d3aa173b5920128995522629eface9a539c17888757bb63e49dc5552bbebc"

      def install
        bin.install "tf"
        bash_completion.install "bin/tf_complete.sh" => "tf"
        zsh_completion.install "bin/tf_complete.zsh" => "_tf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/sorinlg/tf-manage2/releases/download/v0.7.0/tf-manage2_Linux_x86_64.tar.gz"
      sha256 "e4aa1932e296dbf830ebe811dcd76909d6f94ab495a50fb833458fbf18d28b01"
      def install
        bin.install "tf"
        bash_completion.install "bin/tf_complete.sh" => "tf"
        zsh_completion.install "bin/tf_complete.zsh" => "_tf"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/sorinlg/tf-manage2/releases/download/v0.7.0/tf-manage2_Linux_arm64.tar.gz"
      sha256 "0173746f8667db6adafa6d40d465d4bd3f5c0cabed414cea9cb07bd068b2dfd7"
      def install
        bin.install "tf"
        bash_completion.install "bin/tf_complete.sh" => "tf"
        zsh_completion.install "bin/tf_complete.zsh" => "_tf"
      end
    end
  end

  test do
    system "#{bin}/tf", "--help"
  end
end
