# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TfManage2 < Formula
  desc "Terraform workspace manager with enhanced CI/CD detection"
  homepage "https://github.com/sorinlg/tf-manage2"
  version "0.5.0-rc.1"
  license "MIT"

  depends_on "terraform" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sorinlg/tf-manage2/releases/download/v0.5.0-rc.1/tf-manage2_Darwin_x86_64.tar.gz"
      sha256 "12b842d86d34f2c568b05c6299828d07a58984bd25a77616072feed2803440d1"

      def install
        bin.install "tf"
        bash_completion.install "bin/tf_complete.sh" => "tf"
        zsh_completion.install "bin/tf_complete.zsh" => "_tf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sorinlg/tf-manage2/releases/download/v0.5.0-rc.1/tf-manage2_Darwin_arm64.tar.gz"
      sha256 "46341f48a23383a3fdeaa775b65b757f79a812bc4687551d75e7d9e207e26af0"

      def install
        bin.install "tf"
        bash_completion.install "bin/tf_complete.sh" => "tf"
        zsh_completion.install "bin/tf_complete.zsh" => "_tf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/sorinlg/tf-manage2/releases/download/v0.5.0-rc.1/tf-manage2_Linux_x86_64.tar.gz"
      sha256 "003188aa05dcc6507da08ebb57016b2a0f2aaac75b7812f35e17d7fc934c6ec9"
      def install
        bin.install "tf"
        bash_completion.install "bin/tf_complete.sh" => "tf"
        zsh_completion.install "bin/tf_complete.zsh" => "_tf"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/sorinlg/tf-manage2/releases/download/v0.5.0-rc.1/tf-manage2_Linux_arm64.tar.gz"
      sha256 "3cab9d1618920000f9469d94aa4972db9adb9bc5f973dfef19cc6da49b155338"
      def install
        bin.install "tf"
        bash_completion.install "bin/tf_complete.sh" => "tf"
        zsh_completion.install "bin/tf_complete.zsh" => "_tf"
      end
    end
  end

  test do
    system "#{bin}/tf", "--help"
  end
end
